<?php

use Illuminate\Database\Seeder;

class orderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $orders = [
         [
            'order_id'=>1,
            'custid'=>2,
            'empid'=>1,
            'tableno'=>2 ,
            'total'=>2509,
            'cashTender'=>2510,
            'change'=>1,
            'status'=>'paid'
         ],
         [
             'order_id'=>2,
             'custid'=>1,
             'empid'=>2,
             'tableno'=>1 ,
             'total'=>3748,
             'cashTender'=>4000,
             'change'=>252,
             'status'=>'paid'
          ],
          [
             'order_id'=>3,
             'custid'=>1,
             'empid'=>3,
             'tableno'=>4,
             'total'=>2867,
             'cashTender'=>3000,
             'change'=>133,
             'status'=>'paid'
          ],
          [
             'order_id'=>4,
             'custid'=>1,
             'empid'=>1,
             'tableno'=>5,
             'total'=>3352,
             'cashTender'=>3360,
             'change'=>8,
             'status'=>'paid'
          ],
          [
             'order_id'=>5,
             'custid'=>2,
             'empid'=>3,
             'tableno'=>6,
             'total'=>3859,
             'cashTender'=>3900,
             'change'=>41,
             'status'=>'paid'
          ],
             [
            'order_id'=>6,
            'custid'=>3,
            'empid'=>2,
            'tableno'=>6 ,
            'total'=>3130,
            'cashTender'=>3200,
            'change'=>70,
            'status'=>'paid'
         ],
         [
             'order_id'=>7,
             'custid'=>1,
             'empid'=>6,
             'tableno'=>5 ,
             'total'=>3550,
             'cashTender'=>3600,
             'change'=>50,
             'status'=>'paid'
          ],
          [
             'order_id'=>8,
             'custid'=>2,
             'empid'=>5,
             'tableno'=>1,
             'total'=>2659,
             'cashTender'=>3000,
             'change'=>391,
             'status'=>'paid'
          ],
          [
             'order_id'=>9,
             'custid'=>3,
             'empid'=>2,
             'tableno'=>3,
             'total'=>2516,
             'cashTender'=>2520,
             'change'=>4,
             'status'=>'paid'
          ],
          [
             'order_id'=>10,
             'custid'=>1,
             'empid'=>3,
             'tableno'=>4,
             'total'=>3772,
             'cashTender'=>4000,
             'change'=>228,
             'status'=>'paid'
          ],
          [
            'order_id'=>11,
            'custid'=>2,
            'empid'=>1,
            'tableno'=>1,
            'total'=>3438,
            'cashTender'=>3500,
            'change'=>62,
            'status'=>'paid'
         ],
         [
             'order_id'=>12,
             'custid'=>3,
             'empid'=>4,
             'tableno'=>5,
             'total'=>3236,
             'cashTender'=>3240,
             'change'=>4,  
             'status'=>'paid'
          ],
          [
             'order_id'=>13,
             'custid'=>1,
             'empid'=>6,
             'tableno'=>6,
             'total'=>3970,
             'cashTender'=>4000,
             'change'=>30,
             'status'=>'paid'
          ],
          [
             'order_id'=>14,
             'custid'=>2,
             'empid'=>1,
             'tableno'=>3,
             'total'=>3455,
             'cashTender'=>3460,
             'change'=>5,
             'status'=>'paid'
          ],
          [
             'order_id'=>15,
             'custid'=>3,
             'empid'=>3,
             'tableno'=>4,
             'total'=>3688,
             'cashTender'=>3700,
             'change'=>22,
             'status'=>'paid'
          ],
            [
            'order_id'=>16,
            'custid'=>1,
            'empid'=>2,
            'tableno'=>6,
            'total'=>4163,
            'cashTender'=>4200,
            'change'=>37,
            'status'=>'paid'
         ],
         [
             'order_id'=>17,
             'custid'=>2,
             'empid'=>3,
             'tableno'=>1,
             'total'=>3481,
             'cashTender'=>3500,
             'change'=>19,
             'status'=>'paid'
          ],
          [
             'order_id'=>18,
             'custid'=>3,
             'empid'=>5,
             'tableno'=>2,
             'total'=>3751,
             'cashTender'=>3800,
             'change'=>49,
             'status'=>'paid'
          ],
          [
             'order_id'=>19,
             'custid'=>1,
             'empid'=>2,
             'tableno'=>3,
             'total'=>3309,
             'cashTender'=>3310,
             'change'=>1,
             'status'=>'paid'
          ],
          [
             'order_id'=>20,
             'custid'=>2,
             'empid'=>3,
             'tableno'=>4,
             'total'=>3455,
             'cashTender'=>3500,
             'change'=>45,
             'status'=>'paid'
          ],
          [
            'order_id'=>21,
            'custid'=>1,
            'empid'=>1,
            'tableno'=>2 ,
            'total'=>3558,
            'cashTender'=>3660,
            'change'=>2,
            'status'=>'paid'
         ],
         [
             'order_id'=>22,
             'custid'=>2,
             'empid'=>2,
             'tableno'=>1 ,
             'total'=>2991,
             'cashTender'=>3000,
             'change'=>9,
             'status'=>'paid'
          ],
          [
             'order_id'=>23,
             'custid'=>3,
             'empid'=>3,
             'tableno'=>4,
             'total'=>2861,
             'cashTender'=>2870,
             'change'=>9,
             'status'=>'paid'
          ],
          [
             'order_id'=>24,
             'custid'=>1,
             'empid'=>1,
             'tableno'=>5,
             'total'=>2845,
             'cashTender'=>2850,
             'change'=>5,
             'status'=>'paid'
          ],
          [
             'order_id'=>25,
             'custid'=>2,
             'empid'=>3,
             'tableno'=>6,
             'total'=>3678,
             'cashTender'=>3680,
             'change'=>2,
             'status'=>'paid'
          ],
             [
            'order_id'=>26,
            'custid'=>3,
            'empid'=>2,
            'tableno'=>6 ,
            'total'=>3402,
            'cashTender'=>3420,
            'change'=>18,
            'status'=>'paid'
         ],
         [
             'order_id'=>27,
             'custid'=>1,
             'empid'=>6,
             'tableno'=>5 ,
             'total'=>2580,
             'cashTender'=>2600,
             'change'=>20,
             'status'=>'paid'
          ],
          [
             'order_id'=>28,
             'custid'=>2,
             'empid'=>5,
             'tableno'=>1,
             'total'=>2427,
             'cashTender'=>2430,
             'change'=>3,
             'status'=>'paid'
          ],
          [
             'order_id'=>29,
             'custid'=>3,
             'empid'=>2,
             'tableno'=>3,
             'total'=>3418,
             'cashTender'=>3420,
             'change'=>2,
             'status'=>'paid'
          ],
          [
             'order_id'=>30,
             'custid'=>1,
             'empid'=>3,
             'tableno'=>4,
             'total'=>3798,
             'cashTender'=>3800,
             'change'=>2,
             'status'=>'paid'
          ],
        ];
        DB::table('orders')->insert($orders);
    }
}

